### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by EvillarinoP** [lnu/NHibernate.Logging.Serilog#11]
Hi,

I am trying to use this package to log NHibernate events and can't quite make it work.

I already have another logger that logs normal events on a file, and I have it created like this:

**In Web.Config**
```
<add key="serilog:minimum-level" value="Debug" />
<add key="serilog:using:Console" value="Serilog.Sinks.Console" />
<add key="serilog:write-to:Console" />
<add key="serilog:using:File" value="Serilog.Sinks.File" />
<add key="serilog:write-to:File.path" value="c:\<my_logging_path>.log" />
<add key="serilog:write-to:File.outputTemplate" value="{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{ThreadId}] {Level:u} [{EnvironmentUserName}] {SourceContext} {Message:lj}{NewLine}{Exception}" />
<add key="serilog:write-to:File.retainedFileCountLimit" value="2" />
```

Then, on my code, I create the logger in the **NinjectModule** (yes, I know, ninject is kind of old, but this is an old application):

```
Serilog.ILogger serilogLogger = new LoggerConfiguration()
                                .ReadFrom.AppSettings()
                                .Enrich.WithThreadId()
                                .Enrich.WithEnvironmentUserName()
                                .CreateLogger();

Microsoft.Extensions.Logging.ILoggerFactory loggerFactory = new LoggerFactory();

loggerFactory.AddSerilog(serilogLogger);
```

Now, I want to start logging NHibernate events on a different file, so I added the config as you do in your example:

```
<add key="serilog:minimum-level:override:NHibernate" value="Error" />
<add key="serilog:minimum-level:override:NHibernate.SQL" value="Debug" />
<add key="serilog:using:RollingFile" value="Serilog.Sinks.RollingFile" />
<add key="serilog:write-to:RollingFile.path" value="c:\<my_NHibernate_logging_path>.log" />
<add key="serilog:write-to:RollingFile.outputTemplate" value="{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{ThreadId}] {Level:u} [{EnvironmentUserName}] {SourceContext} {Message:lj}{NewLine}{Exception}" />
<add key="serilog:write-to:RollingFile.retainedFileCountLimit" value="10" />
```

Then, I add `NHibernateLogger.SetLoggersFactory(new NHibernate.Logging.Serilog.SerilogLoggerFactory());` in the NinjectModule.

But when I start my application, I don't see any logs whatsoever in the new file. Am I doing something wrong?

**Comment by lnu** [comment]
do you have a sample available on github?

**Comment by dacchid** [comment]
Same here I can NOT get it working either...

App settings are as follows 

  <add key="serilog:using:File" value="Serilog.Sinks.File" />
  <add key="serilog:write-to:File.path" value="C:\Logs\ES.txt" />
  <add key="serilog:write-to:File.fileSizeLimitBytes" value="500000" />
  <add key="serilog:write-to:File.retainedFileCountLimit" value="100" />
  <add key="serilog:write-to:File.rollOnFileSizeLimit" value="true" />
  <add key="serilog:write-to:File.shared" value="true" />
  
  <add key="serilog:minimum-level" value="Error" />
  <add key="serilog:minimum-level:override:NHibernate" value="Debug" />
  <add key="serilog:minimum-level:override:NHibernate.SQL" value="Debug" />

and I have added below the line of code at the startup code of the application

            NHibernateLogger.SetLoggersFactory(new NHibernate.Logging.Serilog.SerilogLoggerFactory());

**Comment by EvillarinoP** [comment]
Hi, 

unfortunately not, I can't share more code on GitHub. But according to the Readme, I did all that is needed to make it work. Could there be any other configurations o dependencies that are blocking this functionality?

**Comment by lnu** [comment]
I've created a [sample](https://github.com/lnu/NHibernateSerilogDemo) asp.net core api.
Have a look and tell me.

**Comment by lnu** [comment]
I guess you either solved the issue or stopped using the library.
