### ISSUE TITLE
It seems Serilog doesn't enable debug level for NHibernate

### ISSUE THREAD

**Issue by ivanzanolla** [lnu/NHibernate.Logging.Serilog#12]
Hi there,

It seems to work but I noticed some logs are missing such as when the SourceContext are

1. NHibernate.Type.StringType
2. NHibernate.Type.DateTimeType
3. NHibernate.SQL
4. etc ...

I means it misses all important information to debug SQL statements.

I believe NHibernate isn't correctly set to debug level even if Serilog is set as minimum level to debug.

I tried to set the debug as minimum level of Serilog. In addition, overriding debug as minimum level of NHibernate in configuration (using Serilog.Sinks.AppSettings) 

>     <add key="serilog:minimum-level" value="Debug" />
>     <add key="serilog:minimum-level:override:NHibernate" value="Debug" /> 
>     <add key="serilog:minimum-level:override:NHibernate.SQL" value="Debug" /> 
or by code
```
                .MinimumLevel.Debug()
                .MinimumLevel.Override("NHibernate", Serilog.Events.LogEventLevel.Debug)
                .MinimumLevel.Override("NHibernate.SQL", Serilog.Events.LogEventLevel.Debug)
```

1. NHibernate version is 5.3.12
2. Serilog version is 2.12.0

I tried to use the code directly in my application instead using the package from nuget, just a try. I noticed as NHibernate.SQL doesn't pass as keyName or type, never. Another try: set IsEnabled always to true. Nothing change. 

Thanks

**Comment by lnu** [comment]
Let me check this tomorrow.

**Comment by ivanzanolla** [comment]
> Let me check this tomorrow.

Hi @lnu,

have you got something about this issue?

Thanks in advance

**Comment by ivanzanolla** [comment]
Found the solution, the set of the factory has to be before any other nhibernate configuration set

**Comment by carlosfc-mendes** [comment]
> Found the solution, the set of the factory has to be before any other nhibernate configuration set

Hello @ivanzanolla ... Do you have some example how do you solve it? What do you mean with "the set of the factory has to be before any other nhibernate configuration set"?

**Comment by carlosfc-mendes** [comment]
> > Found the solution, the set of the factory has to be before any other nhibernate configuration set
> 
> Hello @ivanzanolla ... Do you have some example how do you solve it? What do you mean with "the set of the factory has to be before any other nhibernate configuration set"?

Solved! Here it is some sample code:


            NHibernateLogger.SetLoggersFactory(new NHibernate.Logging.Serilog.SerilogLoggerFactory());

            var nHibernateConfiguration = new NHibernate.Cfg.Configuration();

            // (...) Hibernate Configuration and Mappings

            var sessionFactory = nHibernateConfiguration.BuildSessionFactory();

            services.AddSingleton(sessionFactory);

            services.AddScoped(factory => sessionFactory.OpenSession());

Working on .NET 6 with Serilog configured from appsettings file.
