### ISSUE TITLE
Can we migrate this package license to LGPL 2.1 instead of GPL 3?

### ISSUE THREAD

**Issue by jmaine** [lnu/NHibernate.Logging.Serilog#8]
Can we migrate this package license to LGPL 2.1 instead of GPL 3?

**Comment by lnu** [comment]
Of course. It should have been the same as the nhibernate-core project.
I’ll do it asap.

**Comment by lnu** [comment]
done. I'm not sur if it requires a new build?

**Comment by jmaine** [comment]
Yes, because the new license need to be referenced from the nuget package.

**Comment by lnu** [comment]
new version released.
